INSERT INTO anime (id, title, slug, cover_image, banner_image, synopsis, genres, year, quarter, episode_count, status, rating, popularity)
VALUES 
(
  '1', 
  'Solo Leveling', 
  'solo-leveling', 
  'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-it355ZgzquUd.png', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Solo+Leveling', 
  'They say whatever doesn''t kill you makes you stronger, but that''t the case for the world''s weakest hunter Sung Jinwoo. After being brutally slaughtered by monsters in a high-ranking dungeon, Jinwoo came back with the System, a program only he could see, that''s leveling him up in every way. Now, he''s inspired to discover the secrets behind his powers and the dungeon that spawned them.', 
  '["Action", "Adventure", "Fantasy"]', 
  2024, 
  'Winter', 
  12, 
  'Completed', 
  8.4, 
  250000
),
(
  '2', 
  'Jujutsu Kaisen Season 2', 
  'jujutsu-kaisen-season-2', 
  'https://cdn.myanimelist.net/images/anime/1792/138022l.jpg', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Jujutsu+Kaisen+S2', 
  'The past comes to light when second-year students Satoru Gojo and Suguru Geto are tasked with escorting young Riko Amanai to Master Tengen. But when a non-sorcerer user tries to kill them, their mission to protect the Star Plasma Vessel threatens to turn them into bitter enemies and cement their destinies.', 
  '["Action", "Supernatural", "Fantasy"]', 
  2023, 
  'Summer', 
  23, 
  'Completed', 
  8.8, 
  350000
),
(
  '3', 
  'Frieren: Beyond Journey''s End', 
  'frieren-beyond-journeys-end', 
  'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Frieren', 
  'Elf mage Frieren and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. But Frieren will long outlive the rest of her former party. How will she come to understand what life means to the people around her? Decades after their victory, the funeral of one of her friends confronts Frieren with her own near immortality.', 
  '["Adventure", "Drama", "Fantasy", "Slice of Life"]', 
  2023, 
  'Fall', 
  28, 
  'Completed', 
  9.1, 
  300000
),
(
  '4', 
  'Kaiju No. 8', 
  'kaiju-no-8', 
  'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx153288-25FBfFJzEQ5O.jpg', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Kaiju+No.+8', 
  'In a world plagued by Kaiju, Kafka Hibino works as a monster sweeper. But when a parasitic Kaiju enters his body, Kafka gains the ability to transform into a monster himself. With his newfound powers, Kafka aims to join the Anti-Kaiju Defense Force and keep the promise he made to his childhood friend.', 
  '["Action", "Sci-Fi", "Comedy"]', 
  2024, 
  'Spring', 
  12, 
  'Ongoing', 
  8.2, 
  180000
),
(
  '5', 
  'Demon Slayer: Hashira Training Arc', 
  'demon-slayer-hashira-training-arc', 
  'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx166240-PBV7zukIHW7V.png', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Demon+Slayer', 
  'Tanjiro goes to see the Stone Hashira, Himejima, who intends to prepare him for the battles to come. The training to become a Hashira—a high-ranking member of the Demon Slayer Corps—is intense and demanding. Earning Himejima''s approval seems impossible, but Tanjiro won''t give up!', 
  '["Action", "Supernatural"]', 
  2024, 
  'Spring', 
  8, 
  'Completed', 
  8.1, 
  200000
),
(
  '6', 
  'Mushoku Tensei: Jobless Reincarnation II', 
  'mushoku-tensei-jobless-reincarnation-ii', 
  'https://cdn.myanimelist.net/images/anime/1823/140286l.jpg', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Mushoku+Tensei', 
  'Following the devastating events of the previous season, Rudeus Greyrat wanders the north, aiming to make a name for himself in hopes of finding his missing mother. His journey eventually leads him to the Ranoa University of Magic, where he reunites with a familiar face and embarks on a new chapter of his life.', 
  '["Adventure", "Drama", "Fantasy", "Isekai"]', 
  2023, 
  'Summer', 
  12, 
  'Completed', 
  8.3, 
  160000
),
(
  '7', 
  'Oshi no Ko', 
  'oshi-no-ko', 
  'https://cdn.myanimelist.net/images/anime/1812/134736l.jpg', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Oshi+no+Ko', 
  'When a pregnant young starlet appears in his countryside medical clinic, Dr. Goro is determined to help her deliver safely. But a mysterious figure interferes, and Goro finds himself reborn as the idol''s son. Now, he must navigate the dark and treacherous world of the entertainment industry to uncover the truth.', 
  '["Drama", "Mystery", "Supernatural"]', 
  2023, 
  'Spring', 
  11, 
  'Completed', 
  8.7, 
  280000
),
(
  '8', 
  'Spy x Family Season 2', 
  'spy-x-family-season-2', 
  'https://cdn.myanimelist.net/images/anime/1666/138136l.jpg', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Spy+x+Family', 
  'World peace is at stake, and secret agent Twilight must undergo his most difficult mission yet—pretending to be a family man. Posing as a loving husband and father, he''ll infiltrate an elite school to get close to a high-profile politician. He has the perfect cover, except his wife''s a deadly assassin and neither knows each other''s identity.', 
  '["Action", "Comedy"]', 
  2023, 
  'Fall', 
  12, 
  'Completed', 
  8.2, 
  210000
),
(
  '9', 
  'Dandadan', 
  'dandadan', 
  'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx171018-60q1B6GK2Ghb.jpg', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Dandadan', 
  'Momo Ayase is a high school girl who believes in ghosts but not aliens, while her classmate Okarun believes in aliens but not ghosts. To prove each other wrong, they visit locations associated with both the occult and extraterrestrials, only to discover that both are very real—and incredibly dangerous.', 
  '["Action", "Comedy", "Supernatural"]', 
  2024, 
  'Fall', 
  12, 
  'Upcoming', 
  0, 
  150000
),
(
  '10', 
  'Chainsaw Man', 
  'chainsaw-man', 
  'https://cdn.myanimelist.net/images/anime/1806/126216l.jpg', 
  'https://placehold.co/1920x600/0f172a/f8fafc?text=Chainsaw+Man', 
  'Denji''s a poor young man who''ll do anything for money, even hunting down devils with his pet devil-dog Pochita. He''s a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he''s betrayed by someone he trusts.', 
  '["Action", "Supernatural"]', 
  2022, 
  'Fall', 
  12, 
  'Completed', 
  8.5, 
  400000
);
